### ISSUE TITLE
uninitialized constant ActiveRecord::Import using rails 4.2

### ISSUE THREAD

**Issue by kiddrew** [activeadmin-plugins/active_admin_import#78]
I'm getting this after upgrading to ActiveRecord 4.2.0.  I have active_admin_import 3.0.0.pre and activerecord-import 0.10.0.

**Comment by Fivell** [comment]
@kiddrew , pls attach backtrace

**Comment by Fivell** [comment]
@kiddrew , I updated specs to run with rails4.2, no problems were found

**Comment by kiddrew** [comment]
```
     # /Users/andrew/.rvm/gems/ruby-2.2.1/bundler/gems/active_admin_import-26cecd490631/lib/active_admin_import/dsl.rb:78:in `rescue in block in active_admin_import'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/bundler/gems/active_admin_import-26cecd490631/lib/active_admin_import/dsl.rb:70:in `block in active_admin_import'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/bundler/gems/apipie-rails-4b9bbd30c123/lib/apipie/static_dispatcher.rb:65:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:404:in `call_app!'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:262:in `mock_call!'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:181:in `call!'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:404:in `call_app!'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:262:in `mock_call!'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:181:in `call!'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/bundler/gems/apipie-rails-4b9bbd30c123/lib/apipie/extractor/recorder.rb:132:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:60:in `process'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:26:in `submit'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/rack_test/form.rb:76:in `submit'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/rack_test/node.rb:61:in `click'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/node/element.rb:134:in `block in click'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/node/element.rb:134:in `click'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/node/actions.rb:39:in `click_button'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
     # /Users/andrew/.rvm/gems/ruby-2.2.1/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/locations_import_spec.rb:15:in `block (2 levels) in <top (required)>'

**Comment by Fivell** [comment]
@kiddrew , what is your arguments calling active_admin_import  on your resource?

**Comment by kiddrew** [comment]
Hmm, yeah.  It appears to be a conflict with the `composite_primary_keys` gem.  Everything works if I uninstall that.  I'll close this unless I can determine there's anything to do here.

**Comment by jfeldstein** [comment]
I also had this issue, also in relationship to `composite_primary_keys`. 

@kiddrew, did you ever find a workaround?
